### ISSUE TITLE
Does this still works for current hackpad?

### ISSUE THREAD

**Issue by darbychang** [lkosak/node-hackpad#1]
I have just tried this module and failed. As Hackpad is keeping improved, I wonder if it's my problem or the module's? My code is very simple. Just export https://hackpad.com/Hackpad-API-v1.0-k9bpcEeOo2Q

``` JavaScript
var hackpad = require('hackpad');
var hp = new hackpad(client_id, secret);
hp.export('Hackpad-API-v1.0-k9bpcEeOo2Q', null, 'md', function(err, data){
  console.log(data);
});
```

BTW, the export function seems to accept four arguments, which is inconsistent with the README.md.

**Comment by sergiomajluf** [comment]
It wasn't working for me until I added your fourth null argument, so hey, thanks!

<pre>
var Hackpad = require('hackpad');
var hp = new Hackpad(client_id, secret);
hp.export('k9bpcEeOo2Q', null, 'html', function(err, data){
      console.log(data);
    });
</pre>

**What am I doing different?** The capitalization of the New Hackpad; you need to do that. Also, you don't have to use (but apparently it works, too) the whole URL, just the document ID

**Comment by darbychang** [comment]
@sergiomajluf It's glad that I helped you :) Actually, the capitalization is not the reason (I used a 'h' at the require line). But the document ID did matter. Thanks!
